# Generated by Django 4.1.3 on 2022-11-15 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=260)),
                ('envs', models.JSONField(blank=True, null=True)),
                ('command', models.CharField(max_length=360)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('R', 'Running'), ('F', 'Finished')], default='F', max_length=20)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_run', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.app')),
            ],
        ),
    ]
