# Generated by Django 4.1.3 on 2022-11-15 20:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_container_last_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='last_run',
        ),
        migrations.AddField(
            model_name='app',
            name='last_run',
            field=django_jalali.db.models.jDateTimeField(default=None),
        ),
    ]
