# Generated by Django 4.1.3 on 2022-11-15 20:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_container_last_run_app_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='last_run',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
