# Generated by Django 4.1.3 on 2022-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_historicalapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='full_docker_command',
            field=models.CharField(blank=True, default=None, max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='historicalapp',
            name='full_docker_command',
            field=models.CharField(blank=True, default=None, max_length=360, null=True),
        ),
    ]
